FROM tensorflow/tensorflow:1.12.0-gpu-py3

# nvidia-docker 1.0
LABEL com.nvidia.volumes.needed="nvidia_driver"
LABEL com.nvidia.cuda.version="${CUDA_VERSION}"

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    NVIDIA_REQUIRE_CUDA="cuda>=8.0" \
    LANG=C.UTF-8
    
WORKDIR /home
ADD . .
RUN apt update
RUN apt -y upgrade
RUN apt -y install python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN make

WORKDIR /home/src
RUN python3 download_model.py "117M"