FROM tensorflow/tensorflow:1.12.0-py3

ENV LANG=C.UTF-8
    
WORKDIR /home
ADD . .
RUN apt update
RUN apt -y upgrade
RUN apt -y install python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN make

WORKDIR /home/src
RUN python3 download_model.py "117M"
RUn python3 -m spacy download en