# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpt-2-server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpt-2-server.proto',
  package='gpt2server',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'),
  serialized_pb=_b('\n\x12gpt-2-server.proto\x12\ngpt2server\"^\n\x06GenMsg\x12\x1b\n\x13input_seed_sentence\x18\x01 \x01(\t\x12\x18\n\x10input_model_name\x18\x02 \x01(\t\x12\x1d\n\x15output_generated_text\x18\x03 \x01(\t2<\n\x04gpt2\x12\x34\n\x08Generate\x12\x12.gpt2server.GenMsg\x1a\x12.gpt2server.GenMsg\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_GENMSG = _descriptor.Descriptor(
  name='GenMsg',
  full_name='gpt2server.GenMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_seed_sentence', full_name='gpt2server.GenMsg.input_seed_sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_model_name', full_name='gpt2server.GenMsg.input_model_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_generated_text', full_name='gpt2server.GenMsg.output_generated_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['GenMsg'] = _GENMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenMsg = _reflection.GeneratedProtocolMessageType('GenMsg', (_message.Message,), {
  'DESCRIPTOR' : _GENMSG,
  '__module__' : 'gpt_2_server_pb2'
  # @@protoc_insertion_point(class_scope:gpt2server.GenMsg)
  })
_sym_db.RegisterMessage(GenMsg)


DESCRIPTOR._options = None

_GPT2 = _descriptor.ServiceDescriptor(
  name='gpt2',
  full_name='gpt2server.gpt2',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='Generate',
    full_name='gpt2server.gpt2.Generate',
    index=0,
    containing_service=None,
    input_type=_GENMSG,
    output_type=_GENMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GPT2)

DESCRIPTOR.services_by_name['gpt2'] = _GPT2

# @@protoc_insertion_point(module_scope)
